version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "cd /workspace/backend && if [ ! -f Gemfile ]; then rails new . -d mysql; fi && bundle install && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    working_dir: /workspace/backend
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_volume: