version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "rails server -b 0.0.0.0"
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    working_dir: /workspace/backend
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "3306:3306"

volumes:
  postgres_data: