version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "echo '[docker-compose] Starting Rails setup' && cd /workspace/backend && if [ ! -f Gemfile ]; then echo '[docker-compose] Creating new Rails app' && rails new . -d postgresql; fi && echo '[docker-compose] Installing gems' && bundle install && echo '[docker-compose] Removing old server.pid' && rm -f tmp/pids/server.pid && echo '[docker-compose] Starting Rails server' && rails server -b 0.0.0.0"
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    working_dir: /workspace/backend
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '3306:3306'

volumes:
  postgres_data: